name: Build Levy Debian Package
on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build debian packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Build
      run: |
        ./build_deb_packages.sh
    
    # Get the key like this:
    # gpg --list-secret-keys --keyid-format LONG
    # gpg --export-secret-keys --armor {your_keyId}
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    # - name: Setup Repo
    #   run: ./setup_repo.sh

    # - name: Push package to draft pre-release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     draft: true
    #     prerelease: true
    #     name: New Levy Release
    #     token:  ${{ secrets.OPS_GITHUB_BOT_TOKEN }}
    #     files: |
    #       ./*.deb

