name: Build Levy Debian Package
on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build debian packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Build
      run: |
        ./build_deb_packages.sh
    
    # Get the key like this:
    # gpg --list-secret-keys --keyid-format LONG
    # gpg --export-secret-keys --armor {your_keyId}
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Setup Repo
      run: |
        dpkg-scanpackages --multiversion . > Packages
        gzip -k -f Packages

    - name: Create Release Files
      run: |
        apt-ftparchive release . > Release
        gpg --default-key ${{ secrets.GPG_EMAIL }} -abs -o - Release > Release.gpg
        gpg --default-key ${{ secrets.GPG_EMAIL }} --clearsign -o - Release > InRelease

    - name: Create the Sources List
      run: |
        echo "deb s3://levy-private-tiered-bucket ./" > levy_packages_list_file.list
    
    - name: DEBUG
      run: |
        cat ./levy_packages_list_file.list

    # Configure AWS for Dev, Sandbox (qa1), and develop-delayed
    - name: Configure AWS CLI
      run: |
        aws configure <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY }}
        ${{ secrets.AWS_SECRET_KEY }}
        us-east-1
        text
        EOF
    - name: List files
      run: ls -la
    
    - name: Sync to private s3 bucket
      run: |
          aws s3 cp InRelease s3://levy-private-tiered-bucket
          aws s3 cp Packages s3://levy-private-tiered-bucket
          aws s3 cp Packages.gz s3://levy-private-tiered-bucket
          aws s3 cp Release s3://levy-private-tiered-bucket
          aws s3 cp Release.gpg s3://levy-private-tiered-bucket
          aws s3 cp . s3://levy-private-tiered-bucket/ --recursive --exclude "*" --include "*.deb"
          aws s3 cp . s3://levy-private-tiered-bucket/ --recursive --exclude "*" --include "*.list"
          aws s3 cp public_key.pub s3://levy-private-tiered-bucket
