name: Build Levy Basic Debian Package
on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build debian packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Build
      run: |
        mkdir basic
        printf "\nBuilding levy-test-package-1 deb package...\n"
        dpkg-deb --build --root-owner-group levy-test-package-1

        printf "\nRenaming package according to conventions...\n"
        dpkg-name -o "levy-test-package-1.deb"
        
        mv *.deb ./basic
    
    # Get the key like this:
    # gpg --list-secret-keys --keyid-format LONG
    # gpg --export-secret-keys --armor {your_keyId}
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Setup Basic Repo
      run: |
        cd basic
        dpkg-scanpackages --multiversion . > Packages
        gzip -k -f Packages

    - name: Create Release Files
      run: |
        cd basic
        apt-ftparchive release . > Release
        gpg --default-key ${{ secrets.GPG_EMAIL }} -abs -o - Release > Release.gpg
        gpg --default-key ${{ secrets.GPG_EMAIL }} --clearsign -o - Release > InRelease

    - name: Create the Sources List
      run: |
        cd basic
        echo "deb s3://levy-private-tiered-bucket/basic /" > levy_packages_basic.list
    
    - name: DEBUG
      run: |
        cd basic
        cat ./levy_packages_basic.list

    # Configure AWS
    - name: Configure AWS CLI
      run: |
        aws configure <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY }}
        ${{ secrets.AWS_SECRET_KEY }}
        us-east-1
        text
        EOF
    - name: List files
      run: |
        cd basic
        ls -la
    
    - name: Sync to private s3 bucket
      run: |
        aws s3 cp ./public_key.pub s3://levy-private-tiered-bucket/basic/
        aws s3 sync ./basic s3://levy-private-tiered-bucket/basic
