name: Build Levy Debian Package
on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build debian packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Build
      run: |
        ./build_deb_packages.sh
    
    # Get the key like this:
    # gpg --list-secret-keys --keyid-format LONG
    # gpg --export-secret-keys --armor {your_keyId}
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Setup Repo
      run: |
        dpkg-scanpackages --multiversion . > Packages
        gzip -k -f Packages

    - name: Create Release Files
      run: |
        apt-ftparchive release . > Release
        gpg --default-key ${{ secrets.GPG_EMAIL }} -abs -o - Release > Release.gpg
        gpg --default-key ${{ secrets.GPG_EMAIL }} --clearsign -o - Release > InRelease

    - name: Create the Sources List
      run: |
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/my_ppa.gpg] deb s3://levy-private-tiered-bucket ./" > my_list_file.list
    # - name: Push package to draft pre-release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     draft: true
    #     prerelease: true
    #     name: New Levy Release
    #     token:  ${{ secrets.OPS_GITHUB_BOT_TOKEN }}
    #     files: |
    #       ./*.deb

